### ISSUE TITLE
ColourfulSlider valueRange not working as expected

### ISSUE THREAD

**Issue by Fritiofhedstrom** [SmartToolFactory/Compose-Colorful-Sliders#11]
When the lower value of the valueRange is not 0 the slider is not functioning properly.
In the example below the indicator on the slider for currentValue does not follow the input pointer instead it only travels 0% - 50% of the slider when the thumb/pointer goes 0% - 100%. The output value is in the range of 1f - 2f.

@Preview
@Composable
fun ColorfulSliderDemo() {

    val currentValue = remember{
        mutableStateOf(1f)
    }
    Row {
        Text(text = "currentValue: ${currentValue.value}")
    }
    ColorfulSlider(
        value = currentValue.value,
        thumbRadius = 10.dp,
        trackHeight = 10.dp,
        onValueChange = { it ->
            currentValue.value = it
        },
        valueRange = 1f..3f
    )
}

**Comment by SmartToolFactory** [comment]
Would you mind testing this issue with version 1.2.0 or above? I didn't experience this issue

**Comment by Fritiofhedstrom** [comment]
Yes it does seem to be working now!



Den tors 11 maj 2023 kl 11:04 skrev Smart Tool Factory <
***@***.***>:

**Comment by Fritiofhedstrom** [comment]
This seems to be working now!
