### ISSUE TITLE
After initialisation of SliderWithLabel the label is aligned to the start and not centered to thumb

### ISSUE THREAD

**Issue by SashaProkip** [SmartToolFactory/Compose-Colorful-Sliders#17]
That's how it looks after initialisation: ![Screenshot 2023-04-12 at 14 58 34](https://user-images.githubusercontent.com/110937850/231450192-266b3a9c-0422-4092-b9ad-98c334852a6f.png)
And that's how it looks after interaction with Slider (dragging):  ![Screenshot 2023-04-12 at 15 00 17](https://user-images.githubusercontent.com/110937850/231450624-fad6b17b-f946-4524-befe-d8775d223ef6.png)

**Comment by SmartToolFactory** [comment]
I will look into this.

**Comment by dev-weiqi** [comment]
Hi @SashaProkip   I sent a PR #24   to fix this issue. You can try it out to see if it resolves your problem.
