### ISSUE TITLE
onValueChangeFinished does not seem to work the same as in default Slider

### ISSUE THREAD

**Issue by Wegi** [SmartToolFactory/Compose-Colorful-Sliders#18]
I saw a curious behaviour and thought, it might be a tricky bug. It's easy to reproduce, though. Here is some example code. The difference in behaviour will be below.

```kotlin
@Composable
fun ExampleComponent(
    saturation: Float = 1f,
    onSaturationChanged: (Float) -> Unit = {},
) {
        ColorfulSlider(
            value = saturation,
            onValueChange = onSaturationChanged,
            onValueChangeFinished = { println("onValueChangeFinished $saturation") },
        )

        Slider(
            value = saturation,
            onValueChange = onSaturationChanged,
            onValueChangeFinished = { println("onValueChangeFinished DefaultSlider $saturation") },
        )
}

var saturation by remember { mutableStateOf(0f) }
ExampleComponent(
  saturation = saturation,
  onSaturationChanged = {
    saturation = it
    println("Saturation changed: $it")
  },
)
```

Now if you play around with the sliders, the classic slider will output the current value after dragging is finished just fine. But the `onValueChangeFinished` of the ColorfulSlider will always return 0, no matter what.

Hope this helps reproduce the problem.

**Comment by dev-weiqi** [comment]
Hi @Wegi  I sent a PR #25  to fix this issue. You can try it out to see if it resolves your problem.
