### ISSUE TITLE
Steps not working

### ISSUE THREAD

**Issue by aramsheroyan** [SmartToolFactory/Compose-Colorful-Sliders#2]
Hi! It looks like the steps are not working. I've tried this code but the slider does not snap into the step positions as it does for the default Slider

```  
var sliderPosition by remember { mutableStateOf(0.5f) }
ColorfulSlider(
        value = sliderPosition,
        onValueChange = { it-> sliderPosition = it },
        steps = 8
)
```

**Comment by SmartToolFactory** [comment]
I closed this issue by mistake. I fixed issue #3. I will fix this and add some features like range of solid colors, and a new type of slider that animates thumb shape between circle and rounded rect when i'm available.
