### ISSUE TITLE
Version issue to be included in the build.gradle file

### ISSUE THREAD

**Issue by Nikhil1212** [SmartToolFactory/Compose-Colorful-Sliders#20]
May I know the what needs to be written in place of version in 
dependencies {
  implementation 'com.github.SmartToolFactory:Compose-Colorful-Sliders:<version>'
}

I am unable to use the methods **directly** given in the ReadMe.

**Comment by SmartToolFactory** [comment]
Latest version is 1.2.0 implementation 'com.github.SmartToolFactory:Compose-Colorful-Sliders:1.2.0' would do it. You can check out jitpack.io version on top of README.md for new releases when availalbe.
