### ISSUE TITLE
与 LazyColumn嵌套冲突

### ISSUE THREAD

**Issue by loveRose** [SmartToolFactory/Compose-Colorful-Sliders#30]
将它放在Lazy容器中，会导致滑动冲突，而系统的组件目前已经解决了该冲突问题

**Comment by dev-weiqi** [comment]
Hi @loveRose  I sent a PR https://github.com/SmartToolFactory/Compose-Colorful-Sliders/pull/31 to fix this issue. You can try it out to see if it resolves your problem.

嗨 蜀漢玫瑰，我參考了官方的Slider來修正了此問題，你可以試試看此筆PR https://github.com/SmartToolFactory/Compose-Colorful-Sliders/pull/31 是否可以解決此問題:)
