### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [SmartToolFactory/Compose-Colorful-Sliders#4]
As your repositories name no license, and searching did not reveal any: Could you please specify what license your libraries fall under? No license at all poses a risk to those using your libs, as it a) means "all rights reserved" and b) renders those other projects non-free. I guess this is just an oversight from your end and easily fixed – so thanks in advance!

**Comment by SmartToolFactory** [comment]
I added Apache License 2.0. Thanks for the warning.

**Comment by IzzySoft** [comment]
Thanks a lot! Would you do the same for the other libraries, e.g. [Compose-Extended-Gestures](https://github.com/SmartToolFactory/Compose-Extended-Gestures), as well?

**Comment by SmartToolFactory** [comment]
Sure. Done. I was planning to update gestures with fling gestures which i wrote for Zoom library and now for crop library. I also plan to add snap behavior. And will add propagation option from parent to child or other pass too. If you have any suggestions or custom gestures you wish to be added feel free to open an issue for gesture library.

**Comment by IzzySoft** [comment]
Thanks again! For clarification: I'm no Android dev myself. I've just encountered your libraries used in some FOSS-app. I maintain an APK library checker ([see here](https://gitlab.com/IzzyOnDroid/repo/-/blob/master/lib/README.md)) together with lists of library definitions (the `*.jsonl` files there), so I was adding yours. With the next push, the licenses will show up next to the two libs mentioned above (and as of now, that will be the case already with my repo).

Btw: That library scanner is e.g. used by [F-Droid](https://f-droid.org/) and also by [my repo](https://apt.izzysoft.de/fdroid) to make sure apps comply to FOSS criteria.
