### ISSUE TITLE
onValueChangeFinished cannot respond to clicked

### ISSUE THREAD

**Issue by choristery** [SmartToolFactory/Compose-Colorful-Sliders#8]
Now when Tick is clicked, onValueChangeFinished will not be triggered. If you want to listen in onValueChangeFinished, you will lose this event, but in onValueChange, you cannot deal with scenes with item animations because of frequent calls.

**Comment by nikonhub** [comment]
Hello,

I guess the same call is missing for ColorfulIconSlider  [here](https://github.com/SmartToolFactory/Compose-Colorful-Sliders/blob/7f5a7a56b9c4e04247c455ef62ed14d7f7bafc97/slider/src/main/java/com/smarttoolfactory/slider/ColorfulIconSlider.kt#L228)
